version: "3"

services:
  poffee:
    container_name: poffee
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ELIXIR_VERSION=${ELIXIR_VERSION:-1.14.4}
        - OTP_VERSION=${OTP_VERSION:-25.3.1}
        - DEBIAN_VERSION=${DEBIAN_VERSION:-bullseye-20230227-slim}
        - MIX_ENV=prod
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${WEBAPP_PORT:-4000}:${WEBAPP_PORT:-4000}"
    networks:
      - caddy_network

networks:
  caddy_network:
    name: main_baas
    external: true
