version: "3"

services:
  poffee:
    container_name: poffee
    restart: "${DOCKER_RESTART_POLICY:-always}"
    environment:
      - PHX_SERVER=true
      - PHX_HOST=${PHX_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - ENDPOINT_CHECK_ORIGIN=${ENDPOINT_CHECK_ORIGIN}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CALLBACK_WEBHOOK_URI=${TWITCH_CALLBACK_WEBHOOK_URI}
      - LIVESVELTE_ENABLE_SSR=${LIVESVELTE_ENABLE_SSR}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ELIXIR_VERSION=${ELIXIR_VERSION:-1.15.4}
        - OTP_VERSION=${OTP_VERSION:-25.3.2.5}
        - DEBIAN_VERSION=${DEBIAN_VERSION:-bullseye-20230612-slim}
        - MIX_ENV=prod
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
        - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./log:/app/log
    ports:
      - "${WEBAPP_PORT:-4000}:${WEBAPP_PORT:-4000}"
    networks:
      - caddy_network

networks:
  caddy_network:
    name: caddy_baas
    external: true
