version: "3"

services:
  webapp:
    container_name: poffee
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ELIXIR_VERSION=${ELIXIR_VERSION:-1.14.4}
        - OTP_VERSION=${OTP_VERSION:-25.3.1}
        - DEBIAN_VERSION=${DEBIAN_VERSION:-bullseye-20230227-slim}
        - MIX_ENV=prod
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "${WEBAPP_PORT:-4000}:${WEBAPP_PORT:-4000}"
    networks:
      - poffee_network

networks:
  poffee_network:
