import Config

####################################
# Repo
####################################
config :poffee, Poffee.Repo,
  username: "pgdb_user_poffee",
  password: "pgdb_password_poffee",
  hostname: "localhost",
  database: "poffee_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# use ecto_dev_logger so disabling default logging
# log: false

config :poffee, :generators,
  migration: true,
  binary_id: true,
  sample_binary_id: "11111111-1111-1111-1111-111111111111"

####################################
# Web Endpoint
####################################
# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :poffee, PoffeeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: false,
  debug_errors: true,
  secret_key_base: "iNvUKbkYP3u1pa78Ws16v8eObw4n0eUnUF2qbP5/Psi3DsDiViWvhdiAQ69bdTlR",
  watchers: [
    node: ["build.js", "--watch", cd: Path.expand("../assets", __DIR__)],
    # esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

####################################
# Twitch API
####################################
config :poffee, :twitch, api_client: TwitchApi

####################################
# DB Cache
####################################
# Uncomment the following line to disable DB caching
config :poffee, nebulex_adapter: Nebulex.Adapters.Nil

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :poffee, PoffeeWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/poffee_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

####################################
# Misc
####################################
# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Do not include metadata nor timestamps in development logs
# config :logger, :console, format: "[$level] $message\n"
# config :logger, :default_handler, level: :debug, utc_log: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

import_config "dev.secret.exs"
